name: barrier_gate
description: Venus Sentinel.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # flutter_localizations:
  #   sdk: flutter
  # flutter_localization: ^0.2.2
  auto_size_text: 3.0.0
  badges: 2.0.2
  blurhash_dart: 1.2.1
  cached_network_image: 3.3.1
  collection: 1.18.0
  # file_picker: 8.0.3
  file_picker: ^5.0.0
  flutter_animate: 4.5.0
  flutter_cache_manager: 3.3.1
  flutter_native_splash: 2.3.1
  # flutter_plugin_android_lifecycle: 2.0.20
  font_awesome_flutter: 10.7.0
  from_css_color: 2.0.0
  go_router: 12.1.3
  google_fonts: 6.1.0
  image: 4.0.17
  image_picker: 1.0.4
  # image_picker_android: 0.8.8
  # image_picker_for_web: 3.0.1
  # image_picker_ios: 0.8.8+2
  # image_picker_platform_interface: 2.9.1
  intl: ^0.17.0
  json_path: 0.7.2
  lottie: 2.7.0
  mime_type: 1.0.0
  page_transition: 2.1.0
  path_provider: 2.1.3
  # path_provider_android: 2.2.5
  # path_provider_foundation: 2.4.0
  # path_provider_platform_interface: 2.1.2
  pin_code_fields: 8.0.1
  plugin_platform_interface: 2.1.8
  provider: 6.1.2
  shared_preferences: 2.2.2
  # shared_preferences_android: 2.2.1
  # shared_preferences_foundation: 2.3.4
  # shared_preferences_platform_interface: 2.3.1
  # shared_preferences_web: 2.2.1
  smooth_page_indicator: 1.1.0
  sqflite: 2.2.6
  stop_watch_timer: 3.0.2
  substring_highlight: 1.0.33
  timeago: 3.6.1
  universal_io: 2.2.2
  url_launcher: 6.3.0
  # url_launcher_android: 6.3.4
  # url_launcher_ios: 6.3.1
  # url_launcher_platform_interface: 2.3.2
  video_player: 2.8.6
  # video_player_android: 2.4.16
  # video_player_avfoundation: 2.6.1
  # video_player_platform_interface: 6.2.2
  # video_player_web: 2.3.1
  xml: 6.5.0
  dropdown_button2: 2.3.9
  qr_code_scanner: 1.0.1
  permission_handler: ^11.3.1
  month_year_picker: 0.3.0+1

  # google_mlkit_text_recognition: ^0.7.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  firebase_core: ^2.16.0
  firebase_messaging: ^14.7.0
  google_mlkit_text_recognition: 0.13.0

  camera: 0.10.5+6

  ehp_api:
    git:
      url: https://gitlab.hosxp.net/manoi/ehp-api.git
      ref: main
      auth:
        username: gitlab+deploy-token-2
        password: 99aQxc6gh56vQcr-f6zw
  flutter_localization: ^0.2.0
  flutter_staggered_grid_view: ^0.7.0
  get: ^4.6.6
  flutter_image_compress: ^2.3.0
  shimmer: ^3.0.0
  googleapis: ^13.1.0
  googleapis_auth: ^1.6.0
  flutter_dotenv: ^5.2.1

  flutter_local_notifications: ^18.0.1

dependency_overrides:
  # http: 1.2.1
  uuid: ^4.0.0
  # win32: 5.5.1
  intl: ^0.19.0

dev_dependencies:
  flutter_launcher_icons: 0.13.1
  flutter_lints: 4.0.0
  lints: 4.0.0
  # flutter_test:
  #   sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  web:
    generate: true
  image_path: "assets/images/app_launcher_icon.png"
  adaptive_icon_background: "#424242"
  adaptive_icon_foreground: "assets/images/adaptive_foreground_icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/rive_animations/
    - assets/pdfs/
    - assets/jsons/
    - assets/configis.env

  fonts:
    - family: "sarabun"
      fonts:
        - asset: assets/fonts/Sarabun-Thin.ttf
          weight: 100
        - asset: assets/fonts/Sarabun-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Sarabun-Light.ttf
          weight: 300
        - asset: assets/fonts/Sarabun-Regular.ttf
        - asset: assets/fonts/Sarabun-Medium.ttf
          weight: 500
        - asset: assets/fonts/Sarabun-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Sarabun-Bold.ttf
          weight: 700
        - asset: assets/fonts/Sarabun-ExtraBold.ttf
          weight: 800

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
