// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPb_QWi9jUetE87ZPPmw3JYfFHRi2ZkEs',
    appId: '1:983843065218:web:7b850803e9ee813c8fd39b',
    messagingSenderId: '983843065218',
    projectId: 'village-f1c7a',
    authDomain: 'village-f1c7a.firebaseapp.com',
    storageBucket: 'village-f1c7a.firebasestorage.app',
    measurementId: 'G-ZXKT17FGX9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-6QcoUJ0jpMYMPcTU8zNq3GLVZNx6yqM',
    appId: '1:983843065218:android:eb3617013ff943dc8fd39b',
    messagingSenderId: '983843065218',
    projectId: 'village-f1c7a',
    storageBucket: 'village-f1c7a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQMEIPDMD_YRh02onzEg4WPF32_AjqAnw',
    appId: '1:983843065218:ios:3f806089fd0dd1ec8fd39b',
    messagingSenderId: '983843065218',
    projectId: 'village-f1c7a',
    storageBucket: 'village-f1c7a.firebasestorage.app',
    iosBundleId: 'com.bgs.VenusSentinel',
  );
}
